apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: administrator-admin
  namespace: default
subjects:
- kind: User
  name: administrator
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io 