apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tech-support-operator
  namespace: default
subjects:
- kind: User
  name: tech-support
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: operator
  apiGroup: rbac.authorization.k8s.io 