apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-ingeneer-tech
  namespace: default
subjects:
- kind: User
  name: sre-ingeneer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tech
  apiGroup: rbac.authorization.k8s.io 